name: CI-Windows-x64

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - version.txt
  pull_request: 
    paths-ignore:
      - README.md
      - LICENSE
      - version.txt
  workflow_dispatch: 
    
jobs:

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          
      - name: build
        run: |
          npm install
          npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: upload
        uses: actions/upload-artifact@v3
        with:
            name: vset_win
            path: dist/win-unpacked
          
